language: sh

# latest distribution
# https://docs.travis-ci.com/user/reference/overview/
dist: focal

# just main branch
branches:
  only:
    - master

# dependencies:
install:
  - sudo pip install sphinx sphinxcontrib.images

# script to execute
script:
 - ./makePage

# Generate and deploy documentation to github pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

