#!/bin/bash

# Purpose: creates the doxygen documentation for all the glibraries
# This script is used by TRAVIS
#
# Arguments: none

echo " "
echo " Sphinx version: "$(sphinx-build --version)
echo " "
ddir='build/html'

if [ -d $ddir ]
then
	rm -rf $ddir
fi

echo " "
make html
echo " "
