#!/bin/bash

# Purpose: create the gemc web page
# This script is used by TRAVIS
#
# Arguments: none

echo " "
echo " Sphinx version: "$(sphinx-build --version)
echo " "
ddir='html'

if [ -d $ddir ]
then
	rm -rf $ddir
fi
mkdir -p $ddir

pip install sphinxcontrib-images

echo " Making HTML"
make html
cp -r *.html main.css build $ddir
echo " HTML Completed and copied"

