#!/bin/bash

# Purpose: creates the doxygen documentation for all the glibraries
# This script is used by TRAVIS
#
# Arguments: none

echo " "
echo " Sphinx version: "$(sphinx-build --version)
echo " "
ddir='html'

if [ -d $ddir ]
then
	rm -rf $ddir
fi
mkdir -p $ddir

echo " "
make html
cp -r *.html main.css build $ddir
echo " "
